apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dump-storage-pvc
  namespace: memory-leak-demo
  labels:
    app: dump-volume-manager
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  # OpenShift will use default storage class if not specified

---
apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: dump-volume-critical
value: 1000000
globalDefault: false
description: "High priority for dump volume manager DaemonSet"

---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: dump-volume-manager
  namespace: memory-leak-demo
  labels:
    app: dump-volume-manager
  annotations:
    openshift.io/scc: dump-volume-privileged
spec:
  selector:
    matchLabels:
      app: dump-volume-manager
  template:
    metadata:
      labels:
        app: dump-volume-manager
    spec:
      serviceAccountName: dump-volume-manager
      priorityClassName: dump-volume-critical
      containers:
      - name: volume-manager
        image: busybox:latest
        command:
        - /bin/sh
        - -c
        - |
          echo "Starting dump volume manager..."
          echo "Mounting PV to host /mnt/dump..."
          
          # Create mount point on host if it doesn't exist
          mkdir -p /host/mnt/dump
          
          # Mount the PVC storage to host path using bind mount
          if mountpoint -q /pv-storage; then
            echo "PV is mounted at /pv-storage"
            echo "Creating bind mount to /host/mnt/dump..."
            mount --bind /pv-storage /host/mnt/dump
            echo "Bind mount created successfully"
          else
            echo "ERROR: PV not mounted at /pv-storage"
            exit 1
          fi
          
          # Set permissions
          chmod 777 /host/mnt/dump
          echo "Permissions set to 777"
          
          # Display information
          echo "Available space on /mnt/dump:"
          df -h /host/mnt/dump
          
          echo "Mount information:"
          mount | grep /host/mnt/dump
          
          # Create readiness marker file
          echo "ready" > /host/mnt/dump/.ready
          
          echo "Volume manager running. Keeping pod alive..."
          tail -f /dev/null
        resources:
          requests:
            cpu: 50m
            memory: 64Mi
          limits:
            cpu: 100m
            memory: 128Mi
        volumeMounts:
        - name: host-mnt
          mountPath: /host/mnt
          mountPropagation: Bidirectional
        - name: pv-storage
          mountPath: /pv-storage
        securityContext:
          privileged: true
          capabilities:
            add:
              - SYS_ADMIN
        readinessProbe:
          exec:
            command:
            - sh
            - -c
            - test -f /host/mnt/dump/.ready
          initialDelaySeconds: 5
          periodSeconds: 5
      volumes:
      - name: host-mnt
        hostPath:
          path: /mnt
          type: DirectoryOrCreate
      - name: pv-storage
        persistentVolumeClaim:
          claimName: dump-storage-pvc
      tolerations:
      - effect: NoSchedule
        operator: Exists
      - effect: NoExecute
        operator: Exists
