---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: dump-volume-manager
  namespace: memory-leak-demo
  labels:
    app: dump-volume-manager

---
apiVersion: security.openshift.io/v1
kind: SecurityContextConstraints
metadata:
  name: dump-volume-privileged
  annotations:
    kubernetes.io/description: "SCC for dump volume manager DaemonSet that requires privileged access for bind mounts"
allowHostDirVolumePlugin: true
allowHostIPC: false
allowHostNetwork: false
allowHostPID: false
allowHostPorts: false
allowPrivilegedContainer: true
allowedCapabilities:
  - SYS_ADMIN
defaultAddCapabilities: null
fsGroup:
  type: RunAsAny
priority: 10
readOnlyRootFilesystem: false
requiredDropCapabilities: null
runAsUser:
  type: RunAsAny
seLinuxContext:
  type: RunAsAny
supplementalGroups:
  type: RunAsAny
users: []
groups: []
volumes:
  - configMap
  - downwardAPI
  - emptyDir
  - persistentVolumeClaim
  - projected
  - secret
  - hostPath

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: dump-volume-scc-user
rules:
- apiGroups:
  - security.openshift.io
  resources:
  - securitycontextconstraints
  resourceNames:
  - dump-volume-privileged
  verbs:
  - use

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: dump-volume-scc-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: dump-volume-scc-user
subjects:
- kind: ServiceAccount
  name: dump-volume-manager
  namespace: memory-leak-demo
