apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: nfs-mount-manager
  namespace: heapdump
  labels:
    app: nfs-mount-manager
    app.kubernetes.io/name: nfs-mount-manager
spec:
  source:
    type: Git
    git:
      uri: https://github.com/uniqkod/javadumpmngmt.git
      ref: main
    contextDir: apps/nfs-mount-manager
  strategy:
    type: Docker
    dockerStrategy:
      dockerfilePath: Dockerfile
      noCache: false
      forcePull: false
  output:
    to:
      kind: ImageStreamTag
      name: nfs-mount-manager:latest
  runPolicy: Serial
  successfulBuildsHistoryLimit: 3
  failedBuildsHistoryLimit: 3
