apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: nfs-mount-manager-binary
  namespace: heapdump
  labels:
    app: nfs-mount-manager
spec:
  source:
    type: Binary
    binary: {}
  strategy:
    type: Docker
    dockerStrategy:
      dockerfilePath: Dockerfile.ubi-init
  output:
    to:
      kind: ImageStreamTag
      name: nfs-mount-manager:latest
  runPolicy: Serial
  successfulBuildsHistoryLimit: 3
  failedBuildsHistoryLimit: 3
