apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: volume-mount-controller
  namespace: heapdump
  labels:
    app: volume-mount-controller
    app.kubernetes.io/name: volume-mount-controller
spec:
  source:
    type: Git
    git:
      uri: https://github.com/uniqkod/javadumpmngmt.git
      ref: main
    contextDir: apps/volume-mount-controller
  strategy:
    type: Docker
    dockerStrategy:
      dockerfilePath: Dockerfile
      noCache: false
      forcePull: false
  output:
    to:
      kind: ImageStreamTag
      name: volume-mount-controller:latest
  runPolicy: Serial
  successfulBuildsHistoryLimit: 3
  failedBuildsHistoryLimit: 3
