apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: memory-leak-app
  namespace: memory-leak-demo
  labels:
    app: memory-leak-app
spec:
  host: memory-leak-app.apps.example.com
  port:
    targetPort: 8080
  to:
    kind: Service
    name: memory-leak-service
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Allow
