apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: volume-mount-controller
  namespace: heapdump
  labels:
    app: volume-mount-controller
spec:
  host: volume-mount-controller.apps.example.com
  port:
    targetPort: 8080
  to:
    kind: Service
    name: volume-mount-controller
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Allow
